[workspace]
resolver = "2"
members = ["backend", "middleware", "frontend"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Josh Fairhead"]
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-graphql = "7.0.11"
